### ISSUE TITLE
Use a CI server

### ISSUE THREAD

**Issue by FantasticFiasco** [michael-reichenauer/GitMind#3]
I think you should integrate the project with a CI server. I have experience with AppVeyor but there are a multitude of available free alternatives on whatever platform you choose to build on.

**Comment by michael-reichenauer** [comment]
Yes, I agree once the code has been cleaned up and some relevant tests have been added. Although a CI would encourage better code and tests :-)

**Comment by michael-reichenauer** [comment]
Also thanks for the "nuget restore" hint..

**Comment by FantasticFiasco** [comment]
Just say so and I'll create a AppVeyor build for it.

**Comment by FantasticFiasco** [comment]
I'm not sure the reason to why the exe is checked into the repo, possibly because your are linking to it, but having a CI that has the exe as a artefact might solve the same problem.

**Comment by michael-reichenauer** [comment]
The setup is no longer committed. I am no using the Release attachments instead. GitMind can now check that for latest versions. 

I will consider CI integration in a little while

**Comment by michael-reichenauer** [comment]
This will probably not happen for a while
