### ISSUE TITLE
Open GitMind within repo

### ISSUE THREAD

**Issue by FantasticFiasco** [michael-reichenauer/GitMind#6]
I can currently right-click a directory that is a repo and open GitMind, but I would also like the possibility to right-click within a repo and open GitMind, i.e. not clicking on a directory at all.

**Comment by michael-reichenauer** [comment]
I think this has been fixed in version 0.23 (right-click on empty space within a folder).

**Comment by FantasticFiasco** [comment]
Feature has been verified to work in 0.23. Nice work!
