### ISSUE TITLE
Caret position in commit dialog

### ISSUE THREAD

**Issue by FantasticFiasco** [michael-reichenauer/GitMind#7]
I would like to display the caret position in the commit dialog. For the description input I would also like to display the line index. I am planning to create a PR in the upcoming days.

I would also like to add a EditorConfig to the repo, can you tell me what tab size you are using in your code, because I realize that my Visual Studio is inserting spaces while the rest of the code base is using tabs.

**Comment by michael-reichenauer** [comment]
Ok, that sounds fine. An alternative that you might consider, would be to just add an indicator line below each text box that would function similar to the "Editor Guidelines" (VS extension). That would probably be easier to implement with just a line behind the text boxes and make the text boxes transparent. But if you prefer your proposal, then go ahead.

I usually use tab size 2, but with tabs, everyone can use whatever size they like.

**Comment by FantasticFiasco** [comment]
With a vertical line behind the text box I would have to calculate the horizontal distance the characters would occupy, is that correct?

What is the maximum character count for the subject and the description?

**Comment by michael-reichenauer** [comment]
No, I don't think so, it is most likely just a fixed number since the default boxes have fixed width to handle the recommended text widths (I don't know the numbers now, but can find out tomorrow).

**Comment by michael-reichenauer** [comment]
Nos, there are red indikator lines that indicate recomended width
