### ISSUE TITLE
Display long git commit hash

### ISSUE THREAD

**Issue by FantasticFiasco** [michael-reichenauer/GitMind#8]
When working with git from the command line and one wishes to specify a specific commit, I often find myself copying the commit hash from the commit details pane in GitMind. One thing I constantly wonder however is whether the short hash is unique in the repository. I would love to see that the commit hash I get from GitMind is the long version. Proposed solutions for this could be:

- Make it configurable whether the short or long hash is displayed in GitMind details pane
- Add a copy button next to the hash, and when I click it the long hash is copied to the clipboard

What are your thoughts?

**Comment by michael-reichenauer** [comment]
It is very unlikely that the short hash is not unique and if it is not unique, git will complain when it is used. But I do agree that the long hash should be more accessible.  Currently, it is only shown as a tool tip. But based on your comment I will probably  add a "..." toggle button, which will display the long hash and thus make it accessible for e.g. copying.
Thanks for your comment, it got me to think about at possible solution.

**Comment by michael-reichenauer** [comment]
Now the id is shown as 12 chars and there is a "Copy" button, which copies all 40 chars of the id to the clipboard in the commits details pane.
